#!/bin/bash

# build and run the executable
if [[ "$1" == "run" ]]; then
    if [[ -z "$2" || "$2" == "--debug" || "$2" == "-d" ]]; then
        ./out/debug/main 2>/dev/null || echo "Debug target not found. Run 'mac build' first"
    elif [[ "$2" == "--release" || "$2" == "-r" ]]; then
        ./out/release/main 2>/dev/null || echo "Release target not found. Run 'mac build --release' first"
    else
        echo "Invalid option. Use --debug or --release."
        exit 1
    fi
# build the executable
elif [[ "$1" == "build" ]]; then
    if [[ -z "$2" || "$2" == "--debug" || "$2" == "-d" ]]; then
        mkdir -p out/debug

        # build main target
        clang++ \
        -std=c++17 \
        -Iincludes \
        $(find src -name "*.cpp") \
        -o out/debug/main

        # build test target
        clang++ \
            -std=c++17 \
            -Iincludes \
            -Iextras/googletest/googletest \
            -Iextras/googletest/googletest/include \
            $(find tests -name "*.cpp") \
            src/core.cpp \
            extras/googletest/googletest/src/gtest-all.cc \
            -pthread -o out/debug/test_main
    elif [[ "$2" == "--release" || "$2" == "-r" ]]; then
        mkdir -p out/release

        # build main target
        clang++ \
        -O3 -march=native \
        -std=c++17 \
        -Iincludes \
        $(find src -name "*.cpp") \
        -o out/release/main

        # build test target
        clang++ \
            -std=c++17 \
            -O3 -march=native \
            -Iincludes \
            -Iextras/googletest/googletest \
            -Iextras/googletest/googletest/include \
            $(find tests -name "*.cpp") \
            src/core.cpp \
            extras/googletest/googletest/src/gtest-all.cc \
            -pthread -o out/release/test_main
    elif [[ "$2" == "--all" || "$2" == "-a" ]]; then
        # Build for debug
        ./build build -d

        # Build for release
        ./build build -r
    else
        echo "Invalid option. Use --debug or --release or --all."
        exit 1
    fi
# unittest
elif [[ "$1" == "test" ]]; then
    if [[ -z "$2" || "$2" == "--debug" || "$2" == "-d" ]]; then
        ./out/debug/test_main 2>/dev/null || echo "Debug test target not found. Run 'mac build' first"
    elif [[ "$2" == "--release" || "$2" == "-r" ]]; then
        ./out/release/test_main 2>/dev/null || echo "Release test target not found. Run 'mac build --release' first"
    else
        echo "No test target found!!"
        exit 1;
    fi
# clean the build directory
elif [[ "$1" == "clean" ]]; then
    if [[ "$2" == "--debug" || "$2" == "-d" ]]; then
        rm -rf out/debug
        echo "Cleaned debug build directory."
    elif [[ "$2" == "--release" || "$2" == "-r" ]]; then
        rm -rf out/release
        echo "Cleaned release build directory."
    else
        rm -rf out
        echo "Cleaned all build directories."
    fi
elif [[ "$1" == "help" ]]; then
    glow README.md 2>/dev/null || cat README.md
else
    echo "Usage: ./build [build | run | test | clean | help] [--debug | --release]"
    exit 1
fi
